"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, CircleAlert, Clock3, ExternalLink, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { AccessGuard } from "@/components/access-guard";
import { PageHeader } from "@/components/page-header";
import { useAuth } from "@/components/auth-provider";

type Periodicidade = "DIARIA" | "SEMANAL" | "QUINZENAL" | "MENSAL";
type Prioridade = "ALTA" | "MEDIA" | "BAIXA";
type Status = "PENDENTE" | "EM_ANDAMENTO" | "CONCLUIDA" | "ATRASADA" | "IGNORADA";
type Responsavel = { id: string; nome: string };
type Tarefa = { id: string; nome: string; descricao: string; linksApoio: string[]; periodicidade: Periodicidade; prioridade: Prioridade; ativa: boolean; dataInicio: string; dataEncerramento: string | null; horaPrevista: string | null; diasSemana: number[]; diaMes: number | null; ordinalSemanaMes: number | null; diaSemanaMensal: number | null; responsavelId: string | null; responsavel: Responsavel | null; _count: { ocorrencias: number } };
type Ocorrencia = { id: string; dataPrevista: string; status: Exclude<Status, "ATRASADA">; statusExibicao: Status; observacao: string | null; linksRelacionados: string[]; dataConclusao: string | null; tarefa: Tarefa; usuarioConclusao: Responsavel | null };

const DIAS = [{ v: 1, l: "Seg" }, { v: 2, l: "Ter" }, { v: 3, l: "Qua" }, { v: 4, l: "Qui" }, { v: 5, l: "Sex" }, { v: 6, l: "Sáb" }, { v: 0, l: "Dom" }];
const PERIODICIDADES: Record<Periodicidade, string> = { DIARIA: "Diária", SEMANAL: "Semanal", QUINZENAL: "Quinzenal", MENSAL: "Mensal" };
const STATUS: Record<Status, string> = { PENDENTE: "Pendente", EM_ANDAMENTO: "Em andamento", CONCLUIDA: "Concluída", ATRASADA: "Atrasada", IGNORADA: "Ignorada" };
const formVazio = { nome: "", descricao: "", linksApoio: [""] as string[], periodicidade: "DIARIA" as Periodicidade, prioridade: "MEDIA" as Prioridade, ativa: true, dataInicio: hojeIso(), dataEncerramento: "", horaPrevista: "", diasSemana: [1, 2, 3, 4, 5] as number[], diaMes: "1", regraMensal: "DIA" as "DIA" | "SEMANA", ordinalSemanaMes: "1", diaSemanaMensal: "1", responsavelId: "" };

function hojeIso() { const data = new Date(); return `${data.getFullYear()}-${String(data.getMonth() + 1).padStart(2, "0")}-${String(data.getDate()).padStart(2, "0")}`; }
function somaDias(data: Date, dias: number) { const nova = new Date(data); nova.setDate(nova.getDate() + dias); return nova; }
function isoLocal(data: Date) { return `${data.getFullYear()}-${String(data.getMonth() + 1).padStart(2, "0")}-${String(data.getDate()).padStart(2, "0")}`; }
function dataInput(valor: string | null) { return valor ? valor.slice(0, 10) : ""; }
function formatarData(valor: string) { return new Intl.DateTimeFormat("pt-BR", { weekday: "short", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(valor)); }

export default function GestaoTarefasPage() {
  const { session } = useAuth();
  const [tarefas, setTarefas] = useState<Tarefa[]>([]);
  const [responsaveis, setResponsaveis] = useState<Responsavel[]>([]);
  const [ocorrencias, setOcorrencias] = useState<Ocorrencia[]>([]);
  const [modalTarefa, setModalTarefa] = useState(false);
  const [editandoId, setEditandoId] = useState<string | null>(null);
  const [form, setForm] = useState(formVazio);
  const [ocorrenciaAberta, setOcorrenciaAberta] = useState<Ocorrencia | null>(null);
  const [execucao, setExecucao] = useState({ status: "PENDENTE" as Exclude<Status, "ATRASADA">, observacao: "", linksRelacionados: [""] as string[] });
  const [visao, setVisao] = useState<"HOJE" | "SEMANA" | "ATRASADAS" | "PROXIMAS" | "HISTORICO">("SEMANA");
  const [filtros, setFiltros] = useState({ inicio: isoLocal(somaDias(new Date(), -7)), fim: isoLocal(somaDias(new Date(), 30)), periodicidade: "", status: "", responsavelId: "", tarefaId: "" });
  const [carregando, setCarregando] = useState(true);
  const [salvando, setSalvando] = useState(false);
  const [erro, setErro] = useState<string | null>(null);
  const [mensagem, setMensagem] = useState<string | null>(null);

  const headers = useCallback(() => ({ Authorization: `Bearer ${session?.access_token ?? ""}`, "Content-Type": "application/json" }), [session?.access_token]);
  const carregarTarefas = useCallback(async () => {
    if (!session?.access_token) return;
    const response = await fetch("/api/controle-midia/tarefas", { headers: headers() });
    const json = await response.json();
    if (!response.ok) throw new Error(json.error ?? "Não foi possível carregar as tarefas.");
    setTarefas(json.tarefas); setResponsaveis(json.responsaveis);
  }, [headers, session?.access_token]);
  const carregarOcorrencias = useCallback(async () => {
    if (!session?.access_token) return;
    const query = new URLSearchParams(Object.entries(filtros).filter(([, valor]) => valor));
    const response = await fetch(`/api/controle-midia/tarefas/ocorrencias?${query}`, { headers: headers() });
    const json = await response.json();
    if (!response.ok) throw new Error(json.error ?? "Não foi possível carregar as ocorrências.");
    setOcorrencias(json.ocorrencias);
  }, [filtros, headers, session?.access_token]);
  useEffect(() => { if (!session?.access_token) return; setCarregando(true); setErro(null); Promise.all([carregarTarefas(), carregarOcorrencias()]).catch((e) => setErro(e.message)).finally(() => setCarregando(false)); }, [carregarOcorrencias, carregarTarefas, session?.access_token]);

  const ocorrenciasVisiveis = useMemo(() => {
    const agora = new Date(); const hoje = hojeIso(); const seteDias = somaDias(agora, 7).getTime();
    const ordemStatus: Record<Status, number> = { PENDENTE: 0, ATRASADA: 1, EM_ANDAMENTO: 2, CONCLUIDA: 3, IGNORADA: 4 };
    return ocorrencias.filter((item) => {
      const data = new Date(item.dataPrevista);
      if (visao === "HOJE") return isoLocal(data) === hoje;
      if (visao === "ATRASADAS") return item.statusExibicao === "ATRASADA";
      if (visao === "PROXIMAS") return data.getTime() >= agora.getTime() && data.getTime() <= seteDias && !["CONCLUIDA", "IGNORADA"].includes(item.status);
      if (visao === "HISTORICO") return item.status === "CONCLUIDA";
      const inicioSemana = somaDias(agora, -((agora.getDay() + 6) % 7)); inicioSemana.setHours(0, 0, 0, 0); const fimSemana = somaDias(inicioSemana, 7);
      return data >= inicioSemana && data < fimSemana;
    }).sort((a, b) => ordemStatus[a.statusExibicao] - ordemStatus[b.statusExibicao] || new Date(a.dataPrevista).getTime() - new Date(b.dataPrevista).getTime());
  }, [ocorrencias, visao]);

  function abrirNova() { setEditandoId(null); setForm({ ...formVazio, dataInicio: hojeIso() }); setModalTarefa(true); }
  function abrirEdicao(tarefa: Tarefa) { setEditandoId(tarefa.id); setForm({ nome: tarefa.nome, descricao: tarefa.descricao, linksApoio: tarefa.linksApoio.length ? tarefa.linksApoio : [""], periodicidade: tarefa.periodicidade, prioridade: tarefa.prioridade, ativa: tarefa.ativa, dataInicio: dataInput(tarefa.dataInicio), dataEncerramento: dataInput(tarefa.dataEncerramento), horaPrevista: tarefa.horaPrevista ?? "", diasSemana: tarefa.diasSemana, diaMes: String(tarefa.diaMes ?? 1), regraMensal: tarefa.diaMes ? "DIA" : "SEMANA", ordinalSemanaMes: String(tarefa.ordinalSemanaMes ?? 1), diaSemanaMensal: String(tarefa.diaSemanaMensal ?? 1), responsavelId: tarefa.responsavelId ?? "" }); setModalTarefa(true); }
  function alternarDia(dia: number) { setForm((atual) => ({ ...atual, diasSemana: atual.diasSemana.includes(dia) ? atual.diasSemana.filter((item) => item !== dia) : [...atual.diasSemana, dia] })); }

  async function salvarTarefa(event: FormEvent) {
    event.preventDefault(); setSalvando(true); setErro(null); setMensagem(null);
    try {
      const payload = { ...form, id: editandoId, diaMes: form.periodicidade === "MENSAL" && form.regraMensal === "DIA" ? Number(form.diaMes) : null, ordinalSemanaMes: form.periodicidade === "MENSAL" && form.regraMensal === "SEMANA" ? Number(form.ordinalSemanaMes) : null, diaSemanaMensal: form.periodicidade === "MENSAL" && form.regraMensal === "SEMANA" ? Number(form.diaSemanaMensal) : null };
      const response = await fetch("/api/controle-midia/tarefas", { method: editandoId ? "PATCH" : "POST", headers: headers(), body: JSON.stringify(payload) });
      const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Não foi possível salvar a tarefa.");
      await Promise.all([carregarTarefas(), carregarOcorrencias()]); setModalTarefa(false); setMensagem(editandoId ? "Tarefa atualizada." : "Tarefa criada e recorrências geradas.");
    } catch (e) { setErro(e instanceof Error ? e.message : "Erro inesperado."); } finally { setSalvando(false); }
  }
  async function alternarAtiva(tarefa: Tarefa) { try { const response = await fetch("/api/controle-midia/tarefas", { method: "PATCH", headers: headers(), body: JSON.stringify({ id: tarefa.id, somenteStatus: true, ativa: !tarefa.ativa }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error); await carregarTarefas(); } catch (e) { setErro(e instanceof Error ? e.message : "Erro ao alterar status."); } }
  async function excluir(tarefa: Tarefa) { if (!confirm(`Excluir “${tarefa.nome}” e todo o seu histórico?`)) return; try { const response = await fetch(`/api/controle-midia/tarefas?id=${tarefa.id}`, { method: "DELETE", headers: headers() }); const json = await response.json(); if (!response.ok) throw new Error(json.error); await Promise.all([carregarTarefas(), carregarOcorrencias()]); setMensagem("Tarefa excluída."); } catch (e) { setErro(e instanceof Error ? e.message : "Erro ao excluir tarefa."); } }
  function abrirExecucao(item: Ocorrencia, status?: Exclude<Status, "ATRASADA">) { setOcorrenciaAberta(item); setExecucao({ status: status ?? item.status, observacao: item.observacao ?? "", linksRelacionados: item.linksRelacionados.length ? item.linksRelacionados : [""] }); }
  async function salvarExecucao(event: FormEvent) { event.preventDefault(); if (!ocorrenciaAberta) return; setSalvando(true); try { const response = await fetch("/api/controle-midia/tarefas/ocorrencias", { method: "PATCH", headers: headers(), body: JSON.stringify({ id: ocorrenciaAberta.id, ...execucao }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error); await carregarOcorrencias(); setOcorrenciaAberta(null); setMensagem(execucao.status === "CONCLUIDA" ? "Tarefa concluída." : "Ocorrência atualizada."); } catch (e) { setErro(e instanceof Error ? e.message : "Erro ao atualizar ocorrência."); } finally { setSalvando(false); } }

  return <AccessGuard permissions={["podeVisualizarTarefasMidia"]}><div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><PageHeader title="Gestão de Tarefas" description="Cadastre rotinas recorrentes e acompanhe a execução da operação de mídia e marketing." /><button type="button" onClick={abrirNova} className="inline-flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Nova tarefa</button></div>
    {erro && <div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><CircleAlert className="h-4 w-4" />{erro}</div>}{mensagem && <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{mensagem}</div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(["HOJE", "SEMANA", "ATRASADAS", "PROXIMAS", "HISTORICO"] as const).map((item) => <button key={item} onClick={() => setVisao(item)} className={`rounded-xl border p-4 text-left transition ${visao === item ? "border-slate-900 bg-slate-900 text-white" : "border-slate-200 bg-white text-slate-700 hover:border-slate-400"}`}><p className="text-xs font-semibold uppercase tracking-wide opacity-70">{item === "HISTORICO" ? "Histórico" : item === "PROXIMAS" ? "Próximas" : item === "ATRASADAS" ? "Atrasadas" : item === "SEMANA" ? "Esta semana" : "Hoje"}</p><p className="mt-2 text-2xl font-bold">{ocorrencias.filter((o) => item === "ATRASADAS" ? o.statusExibicao === "ATRASADA" : item === "HISTORICO" ? o.status === "CONCLUIDA" : item === "HOJE" ? isoLocal(new Date(o.dataPrevista)) === hojeIso() : true).length}</p></button>)}</section>
    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-900"><Search className="h-4 w-4" /> Filtros</div><div className="grid gap-3 md:grid-cols-3 lg:grid-cols-6"><label className="text-xs font-medium text-slate-600">De<input type="date" value={filtros.inicio} onChange={(e) => setFiltros({ ...filtros, inicio: e.target.value })} className="mt-1 w-full rounded-md border border-slate-300 px-2 py-2 text-sm" /></label><label className="text-xs font-medium text-slate-600">Até<input type="date" value={filtros.fim} onChange={(e) => setFiltros({ ...filtros, fim: e.target.value })} className="mt-1 w-full rounded-md border border-slate-300 px-2 py-2 text-sm" /></label><FiltroSelect label="Periodicidade" value={filtros.periodicidade} onChange={(v) => setFiltros({ ...filtros, periodicidade: v })} options={Object.entries(PERIODICIDADES)} /><FiltroSelect label="Status" value={filtros.status} onChange={(v) => setFiltros({ ...filtros, status: v })} options={Object.entries(STATUS)} /><FiltroSelect label="Responsável" value={filtros.responsavelId} onChange={(v) => setFiltros({ ...filtros, responsavelId: v })} options={responsaveis.map((r) => [r.id, r.nome])} /><FiltroSelect label="Tarefa" value={filtros.tarefaId} onChange={(v) => setFiltros({ ...filtros, tarefaId: v })} options={tarefas.map((t) => [t.id, t.nome])} /></div></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Ocorrências previstas</h2><p className="text-sm text-slate-500">{ocorrenciasVisiveis.length} itens nesta visualização</p></div><CalendarDays className="h-5 w-5 text-slate-400" /></div>{carregando ? <p className="p-8 text-center text-sm text-slate-500">Carregando tarefas...</p> : !ocorrenciasVisiveis.length ? <p className="p-8 text-center text-sm text-slate-500">Nenhuma ocorrência encontrada para esta visualização.</p> : <div className="divide-y divide-slate-100">{ocorrenciasVisiveis.map((item) => <article key={item.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><div className={`h-10 w-1 shrink-0 rounded-full ${item.tarefa.prioridade === "ALTA" ? "bg-red-500" : item.tarefa.prioridade === "MEDIA" ? "bg-amber-400" : "bg-emerald-500"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-900">{item.tarefa.nome}</h3><StatusBadge status={item.statusExibicao} /><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{PERIODICIDADES[item.tarefa.periodicidade]}</span></div><p className="mt-1 line-clamp-2 text-sm text-slate-600">{item.tarefa.descricao}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{formatarData(item.dataPrevista)}</span><span>Responsável: {item.tarefa.responsavel?.nome ?? "Não definido"}</span>{item.usuarioConclusao && <span>Concluída por {item.usuarioConclusao.nome}</span>}</div></div><div className="flex shrink-0 flex-wrap gap-2">{item.tarefa.linksApoio.map((link, indice) => <a key={link} href={link} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700"><ExternalLink className="h-3.5 w-3.5" /> Apoio {item.tarefa.linksApoio.length > 1 ? indice + 1 : ""}</a>)}{item.status !== "CONCLUIDA" && <button onClick={() => abrirExecucao(item, "CONCLUIDA")} className="inline-flex items-center gap-1 rounded-md bg-emerald-700 px-3 py-2 text-xs font-medium text-white"><CheckCircle2 className="h-3.5 w-3.5" /> Concluir</button>}<button onClick={() => abrirExecucao(item)} className="rounded-md border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700">Detalhes</button></div></article>)}</div>}</section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">Tarefas cadastradas</h2><p className="text-sm text-slate-500">{tarefas.length} rotinas configuradas</p></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{tarefas.map((tarefa) => <article key={tarefa.id} className={`rounded-lg border p-4 ${tarefa.ativa ? "border-slate-200" : "border-slate-200 bg-slate-50 opacity-70"}`}><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{tarefa.nome}</h3><p className="mt-1 text-xs text-slate-500">{PERIODICIDADES[tarefa.periodicidade]} · prioridade {tarefa.prioridade.toLowerCase()} · {tarefa._count.ocorrencias} ocorrências</p></div><button type="button" role="switch" aria-checked={tarefa.ativa} onClick={() => void alternarAtiva(tarefa)} className={`relative h-6 w-11 rounded-full ${tarefa.ativa ? "bg-emerald-600" : "bg-slate-300"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${tarefa.ativa ? "left-6" : "left-1"}`} /></button></div><p className="mt-3 line-clamp-2 text-sm text-slate-600">{tarefa.descricao}</p><div className="mt-4 flex gap-2"><button onClick={() => abrirEdicao(tarefa)} className="inline-flex flex-1 items-center justify-center gap-1 rounded-md border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700"><Pencil className="h-3.5 w-3.5" /> Editar</button><button onClick={() => void excluir(tarefa)} className="inline-flex items-center justify-center rounded-md border border-red-200 px-3 py-2 text-red-700"><Trash2 className="h-3.5 w-3.5" /></button></div></article>)}</div></section>
    {modalTarefa && <Modal onClose={() => setModalTarefa(false)}><form onSubmit={salvarTarefa} className="space-y-5"><ModalTitulo titulo={editandoId ? "Editar tarefa" : "Nova tarefa"} descricao="Configure os dados e a regra de recorrência." onClose={() => setModalTarefa(false)} /><div className="grid gap-4 md:grid-cols-2"><Campo label="Nome da tarefa"><input required value={form.nome} onChange={(e) => setForm({ ...form, nome: e.target.value })} className="input" /></Campo><Campo label="Responsável"><select value={form.responsavelId} onChange={(e) => setForm({ ...form, responsavelId: e.target.value })} className="input"><option value="">Não definido</option>{responsaveis.map((r) => <option key={r.id} value={r.id}>{r.nome}</option>)}</select></Campo><Campo label="Descrição" wide><textarea required rows={3} value={form.descricao} onChange={(e) => setForm({ ...form, descricao: e.target.value })} className="input resize-none" /></Campo><Campo label="Links de apoio (opcional)" wide><ListaLinks links={form.linksApoio} onChange={(linksApoio) => setForm({ ...form, linksApoio })} /></Campo><Campo label="Periodicidade"><select value={form.periodicidade} onChange={(e) => setForm({ ...form, periodicidade: e.target.value as Periodicidade, diasSemana: e.target.value === "SEMANAL" ? [1] : form.diasSemana })} className="input">{Object.entries(PERIODICIDADES).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Campo><Campo label="Prioridade"><select value={form.prioridade} onChange={(e) => setForm({ ...form, prioridade: e.target.value as Prioridade })} className="input"><option value="ALTA">Alta</option><option value="MEDIA">Média</option><option value="BAIXA">Baixa</option></select></Campo><Campo label="Data de início"><input required type="date" value={form.dataInicio} onChange={(e) => setForm({ ...form, dataInicio: e.target.value })} className="input" /></Campo><Campo label="Data de encerramento (opcional)"><input type="date" min={form.dataInicio} value={form.dataEncerramento} onChange={(e) => setForm({ ...form, dataEncerramento: e.target.value })} className="input" /></Campo></div><RegraRecorrencia form={form} setForm={setForm} alternarDia={alternarDia} /><label className="flex items-center gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700"><input type="checkbox" checked={form.ativa} onChange={(e) => setForm({ ...form, ativa: e.target.checked })} />Tarefa ativa</label><div className="flex justify-end gap-2"><button type="button" onClick={() => setModalTarefa(false)} className="rounded-md border border-slate-300 px-4 py-2 text-sm">Cancelar</button><button disabled={salvando} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{salvando ? "Salvando..." : "Salvar tarefa"}</button></div></form></Modal>}
    {ocorrenciaAberta && <Modal onClose={() => setOcorrenciaAberta(null)}><form onSubmit={salvarExecucao} className="space-y-5"><ModalTitulo titulo={ocorrenciaAberta.tarefa.nome} descricao={formatarData(ocorrenciaAberta.dataPrevista)} onClose={() => setOcorrenciaAberta(null)} /><Campo label="Status"><select value={execucao.status} onChange={(e) => setExecucao({ ...execucao, status: e.target.value as Exclude<Status, "ATRASADA"> })} className="input"><option value="PENDENTE">Pendente</option><option value="EM_ANDAMENTO">Em andamento</option><option value="CONCLUIDA">Concluída</option><option value="IGNORADA">Ignorada</option></select></Campo><Campo label="Observação"><textarea rows={4} value={execucao.observacao} onChange={(e) => setExecucao({ ...execucao, observacao: e.target.value })} className="input resize-none" /></Campo><Campo label="Links relacionados"><ListaLinks links={execucao.linksRelacionados} onChange={(linksRelacionados) => setExecucao({ ...execucao, linksRelacionados })} /></Campo><button disabled={salvando} className="w-full rounded-md bg-slate-900 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{salvando ? "Salvando..." : "Salvar ocorrência"}</button></form></Modal>}
  </div></AccessGuard>;
}

function RegraRecorrencia({ form, setForm, alternarDia }: { form: typeof formVazio; setForm: (form: typeof formVazio) => void; alternarDia: (dia: number) => void }) { return <div className="rounded-xl border border-blue-100 bg-blue-50/60 p-4"><h3 className="text-sm font-semibold text-slate-900">Regra de recorrência</h3>{(form.periodicidade === "DIARIA" || form.periodicidade === "SEMANAL") && <div className="mt-3"><p className="mb-2 text-xs font-medium text-slate-600">{form.periodicidade === "DIARIA" ? "Dias de execução" : "Dia da semana"}</p><div className="flex flex-wrap gap-2">{DIAS.map((dia) => <button type="button" key={dia.v} onClick={() => { if (form.periodicidade === "SEMANAL") setForm({ ...form, diasSemana: [dia.v] }); else alternarDia(dia.v); }} className={`rounded-md border px-3 py-2 text-xs font-medium ${form.diasSemana.includes(dia.v) ? "border-blue-700 bg-blue-700 text-white" : "border-slate-300 bg-white text-slate-600"}`}>{dia.l}</button>)}</div></div>}{form.periodicidade === "QUINZENAL" && <p className="mt-3 text-sm text-slate-600">A primeira ocorrência será na data de início e se repetirá a cada 14 dias.</p>}{form.periodicidade === "MENSAL" && <div className="mt-3 grid gap-3 md:grid-cols-2"><Campo label="Tipo de regra"><select value={form.regraMensal} onChange={(e) => setForm({ ...form, regraMensal: e.target.value as "DIA" | "SEMANA" })} className="input"><option value="DIA">Dia do mês</option><option value="SEMANA">Semana e dia</option></select></Campo>{form.regraMensal === "DIA" ? <Campo label="Dia"><input type="number" min={1} max={31} value={form.diaMes} onChange={(e) => setForm({ ...form, diaMes: e.target.value })} className="input" /></Campo> : <><Campo label="Ocorrência"><select value={form.ordinalSemanaMes} onChange={(e) => setForm({ ...form, ordinalSemanaMes: e.target.value })} className="input"><option value="1">Primeira</option><option value="2">Segunda</option><option value="3">Terceira</option><option value="4">Quarta</option><option value="5">Quinta</option></select></Campo><Campo label="Dia"><select value={form.diaSemanaMensal} onChange={(e) => setForm({ ...form, diaSemanaMensal: e.target.value })} className="input">{DIAS.map((d) => <option key={d.v} value={d.v}>{d.l}</option>)}</select></Campo></>}</div>}<div className="mt-3 max-w-xs"><Campo label="Hora prevista (opcional)"><input type="time" value={form.horaPrevista} onChange={(e) => setForm({ ...form, horaPrevista: e.target.value })} className="input" /></Campo></div></div>; }
function FiltroSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[][] }) { return <label className="text-xs font-medium text-slate-600">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded-md border border-slate-300 bg-white px-2 py-2 text-sm"><option value="">Todos</option>{options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
function ListaLinks({ links, onChange }: { links: string[]; onChange: (links: string[]) => void }) { return <div className="space-y-2">{links.map((link, indice) => <div key={indice} className="flex gap-2"><input type="url" placeholder="https://..." value={link} onChange={(e) => onChange(links.map((item, atual) => atual === indice ? e.target.value : item))} className="input" /><button type="button" aria-label="Remover link" disabled={links.length === 1} onClick={() => onChange(links.filter((_, atual) => atual !== indice))} className="rounded-md border border-red-200 px-3 text-red-700 disabled:cursor-not-allowed disabled:opacity-30"><Trash2 className="h-4 w-4" /></button></div>)}<button type="button" onClick={() => onChange([...links, ""])} className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700"><Plus className="h-3.5 w-3.5" /> Adicionar link</button></div>; }
function StatusBadge({ status }: { status: Status }) { const cor = status === "CONCLUIDA" ? "bg-emerald-100 text-emerald-700" : status === "ATRASADA" ? "bg-red-100 text-red-700" : status === "EM_ANDAMENTO" ? "bg-blue-100 text-blue-700" : status === "IGNORADA" ? "bg-slate-200 text-slate-600" : "bg-amber-100 text-amber-700"; return <span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${cor}`}>{STATUS[status]}</span>; }
function Campo({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`block text-sm font-medium text-slate-700 ${wide ? "md:col-span-2" : ""}`}>{label}<div className="mt-1.5">{children}</div></label>; }
function Modal({ onClose, children }: { onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button type="button" aria-label="Fechar" onClick={onClose} className="absolute inset-0 bg-slate-950/60" /><div className="relative z-10 max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-white p-5 shadow-2xl sm:p-6">{children}</div></div>; }
function ModalTitulo({ titulo, descricao, onClose }: { titulo: string; descricao: string; onClose: () => void }) { return <div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold text-slate-900">{titulo}</h2><p className="mt-1 text-sm text-slate-500">{descricao}</p></div><button type="button" onClick={onClose} className="rounded-md p-2 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5" /></button></div>; }
